In [1]:
from social_graph.pipeline import *
from social_graph.metrics import *

In [2]:
conn = sqlite3.connect('data/database_server.db')
follow = pd.read_sql("SELECT * FROM follow", conn)
follow.head()

   user_id  follower_id  id  action  round
0      529          145   1  follow      1
1      177          496   2  follow      2
2      272          481   3  follow      2
3      192            5   4  follow      2
4      230          576   5  follow      3

In [3]:
posts = pd.read_sql("SELECT * FROM post", conn)
posts.head()

,id,tweet,post_img,user_id,comment_to,thread_id,round,news_id,shared_from,image_id,reaction_count
0,1,I'm really excited about the possibilities tha...,None,961,-1,1,1,None,-1,None,2
1,2,AI development is an exciting field that has t...,None,961,-1,2,1,None,-1,None,0
2,3,I just finished reading The 4Hour Workweek by ...,None,952,-1,3,1,None,-1,None,5
3,4,@LouisHarris I've heard a lot of good things a...,None,27,3,3,1,None,-1,None,1
4,5,@LouisHarris I just finished reading The 4Hour...,None,27,3,3,1,None,-1,None,1

In [4]:
len(follow)

2450

In [5]:
len(posts)

21240

In [6]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)

               name
0   sqlite_sequence
1          hashtags
2     post_hashtags
3          mentions
4          emotions
5     post_emotions
6            rounds
7            follow
8         reactions
9          websites
10         articles
11  recommendations
12           voting
13    user_interest
14        interests
15      post_topics
16        user_mgmt
17           images
18             post
19   article_topics
20   post_sentiment
21    post_toxicity

In [7]:
pd.read_sql("SELECT * FROM user_mgmt;", conn)

,id,username,email,password,user_type,leaning,age,oe,co,ex,...,frecsys_type,round_actions,gender,nationality,toxicity,is_page,left_on,daily_activity_level,profession,activity_profile
0,1,Admin,admin@y-not.social,pbkdf2:sha256:1000000$p5aw8n4lKUZ33ZRE$26594a3...,user,none,0,None,None,None,...,default,3,None,None,none,0,None,1,None,None
1,2,LisaCook,LisaCook@ysocial.it,LisaCook,CYFRAGOVPL/Llama-PLLuM-70B-chat-250801,democrat,16,consistent/cautious,extravagant/careless,solitary/reserved,...,CommonNeighbors,6,female,American,none,0,None,4,Student,Casual Scroller
2,3,SherryMartin,SherryMartin@ysocial.it,SherryMartin,CYFRAGOVPL/Llama-PLLuM-70B-chat-250801,democrat,45,consistent/cautious,extravagant/careless,solitary/reserved,...,CommonNeighbors,2,female,American,none,0,None,4,Miner,Coffee Break User
3,4,TracyMcneil,TracyMcneil@ysocial.it,TracyMcneil,CYFRAGOVPL/Llama-PLLuM-70B-chat-250801,republican,17,consistent/cautious,efficient/organized,outgoing/energetic,...,CommonNeighbors,9,female,American,none,0,None,2,Student,Evening Commentator
4,5,JeremiahDuffy,JeremiahDuffy@ysocial.it,JeremiahDuffy,CYFRAGOVPL/Llama-PLLuM-70B-chat-250801,democrat,55,inventive/curious,efficient/organized,solitary/reserved,...,CommonNeighbors,5,male,American,none,0,None,4,Student,Always On
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,997,ValerieRodgers,ValerieRodgers@ysocial.it,ValerieRodgers,CYFRAGOVPL/Llama-PLLuM-70B-chat-250801,democrat,18,inventive/curious,efficient/organized,outgoing/energetic,...,CommonNeighbors,9,female,American,none,0,None,2,Accountant,Always On
997,998,MelanieFranco,MelanieFranco@ysocial.it,MelanieFranco,CYFRAGOVPL/Llama-PLLuM-70B-chat-250801,democrat,14,consistent/cautious,efficient/organized,solitary/reserved,...,CommonNeighbors,1,female,American,none,0,None,3,Student,Casual Scroller
998,999,PatrickWhite,PatrickWhite@ysocial.it,PatrickWhite,CYFRAGOVPL/Llama-PLLuM-70B-chat-250801,democrat,18,inventive/curious,efficient/organized,solitary/reserved,...,CommonNeighbors,4,male,American,none,0,None,3,Professor,Global Connector
999,1000,BrettDavis,BrettDavis@ysocial.it,BrettDavis,CYFRAGOVPL/Llama-PLLuM-70B-chat-250801,democrat,23,consistent/cautious,efficient/organized,solitary/reserved,...,CommonNeighbors,6,male,American,none,0,None,4,Call Center Agent,Global Connector
1000,1001,DonaldLopez,DonaldLopez@ysocial.it,DonaldLopez,CYFRAGOVPL/Llama-PLLuM-70B-chat-250801,centrist,17,inventive/curious,efficient/organized,outgoing/energetic,...,CommonNeighbors,1,male,American,none,0,None,3,Student,Coffee Break User